# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.1.0
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-04-20T05:21:39Z"
  labels:
    app: blog
  name: blog
spec: 
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP   
    targetPort: 80
  selector:
    app: blog
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-04-20T05:21:39Z"
  labels:
    app: blog
  name: blog
spec:
  containers:
  - args:
    - mysqld
    command:
    - docker-entrypoint.sh
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: MYSQL_DATABASE
      value: magazine
    - name: MARIADB_MAJOR
      value: "10.5"
    - name: MARIADB_VERSION
      value: 1:10.5.9+maria~focal
    - name: GOSU_VERSION
      value: "1.12"
    - name: GPG_KEYS
      value: 177F4010FE56CA3336300305F1656F24C74CD1D8
    - name: MYSQL_USER
      value: magazine
    - name: MYSQL_PASSWORD
      value: 1maGazine!
    - name: MYSQL_ROOT_PASSWORD
      value: 1maGazine!
    image: docker.io/library/mariadb:10.5
    name: blogdb1
    ports:
    - containerPort: 80
      protocol: TCP
      targetPort: 32386
    - containerPort: 3306
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions:
        level: s0:c13,c2
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: blog-wpdbvol-pvc
    workingDir: /
  - args:
    - apache2-foreground
    command:
    - docker-entrypoint.sh
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: PHP_URL
      value: https://www.php.net/distributions/php-7.4.16.tar.xz
    - name: PHP_SHA256
      value: 1c16cefaf88ded4c92eed6a8a41eb682bb2ef42429deb55f1c4ba159053fb98b
    - name: PHP_CPPFLAGS
      value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
    - name: PHP_VERSION
      value: 7.4.16
    - name: APACHE_CONFDIR
      value: /etc/apache2
    - name: APACHE_ENVVARS
      value: /etc/apache2/envvars
    - name: GPG_KEYS
      value: 42670A7FE4D0441C8E4632349E4FDC074A4EF02D 5A52880781F755608BF815FC910DEB46F53EA312
    - name: WORDPRESS_DB_PASSWORD
      value: 1maGazine!
    - name: WORDPRESS_TABLE_PREFIX
      value: cz
    - name: WORDPRESS_DB_HOST
      value: blog
    - name: WORDPRESS_DB_NAME
      value: magazine
    - name: WORDPRESS_DB_USER
      value: magazine
    - name: PHP_INI_DIR
      value: /usr/local/etc/php
    - name: PHP_EXTRA_CONFIGURE_ARGS
      value: --with-apxs2 --disable-cgi
    - name: PHP_ASC_URL
      value: https://www.php.net/distributions/php-7.4.16.tar.xz.asc
    - name: PHPIZE_DEPS
      value: "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake
        \t\tpkg-config \t\tre2c"
    - name: PHP_EXTRA_BUILD_DEPS
      value: apache2-dev
    - name: PHP_LDFLAGS
      value: -Wl,-O1 -pie
    - name: PHP_CFLAGS
      value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
    - name: WORDPRESS_DEBUG
      value: "0"
    image: docker.io/library/wordpress:latest
    name: blogweb1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /var/www/html
      name: blog-wordpress-pvc
    workingDir: /var/www/html
  dnsConfig: {}
  restartPolicy: Always
  volumes:
  - name: blog-wpdbvol-pvc
    persistentVolumeClaim:
      claimName: blog-wpdbvol
  - name: blog-wordpress-pvc
    persistentVolumeClaim:
      claimName: blog-wordpress
status: {}

